# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baseball', '0004_auto_20150607_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='batter_contact',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batter_double',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batter_flyout',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batter_groundout',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batter_homerun',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batter_single',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batter_speed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batter_strikeout',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batter_triple',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batter_walk',
        ),
        migrations.RemoveField(
            model_name='player',
            name='eye',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_contact',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_control',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_double',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_flyout',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_groundout',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_homerun',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_movement',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_power',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_single',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_strikeout',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_triple',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_walk',
        ),
        migrations.RemoveField(
            model_name='player',
            name='power',
        ),
        migrations.RemoveField(
            model_name='player',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='batter_double_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='batter_hit_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='batter_home_run_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='pitcher_hit_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='pitcher_home_run_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='power_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='speed_rating',
            field=models.IntegerField(default=1),
        ),
    ]
